config/routes.rb
DoLater::Application.routes.draw do
  resources :lists

  

end

app/models/list.rb
class List < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
    sleep 1
    @incomplete_tasks = List.where(complete: false)
    @complete_tasks = List.where(complete: true)
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        # format.html { redirect_to @list, notice: 'List was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @list }
        format.js
      else
        # format.html { render action: 'new' }
        # format.json { render json: @list.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        # format.html { redirect_to @list, notice: 'List was successfully updated.' }
        # format.json { head :no_content }
        format.js
      else
        # format.html { render action: 'edit' }
        # format.json { render json: @list.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      # format.html { redirect_to lists_url }
      # format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:task, :complete)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DoLater</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= form_for @list, remote: true do |f|%>
  <% if @list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
      <% @list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task %><br>
    <%= f.text_field :task %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<!-- TODO: ajaxy update button, change "list" to "task" across pages, twilio, slim, gitignore, bootstrap,  -->

app/views/lists/_list.html.erb
<%= form_for list, remote: true do |f| %>
  <%= f.check_box :complete %>
  <%= f.submit "Update"%>
  <%= f.label :complete, list.task %>
  <%= link_to "(remove)", list, method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
<% end %>

<!-- TODO: analyze this code -->

app/views/lists/create.js.erb
$('#new_list').remove();
// $('#new_list').fadeOut("500", function() { $(this).remove(); });
$('#form_link').show();
$('#incomplete_tasks').append('<%= j render(@list) %>');
$('#edit_list_<%= @list.id %>').submitOnCheck().hide().fadeIn("500");

// $('#edit_list_<%= @list.id %>').fadeOut("500", function() { $(this).remove(); });

app/views/lists/destroy.js.erb
$('#edit_list_<%= @list.id %>').fadeOut("500", function() { 
	$(this).remove();
});

// $(function () {
//   $('.edit_list input[type=submit]').remove();
//   $('.edit_list input[type=checkbox]').click(function () {
//     $(this).parent('form').submit();
//   });  
// });

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.erb
<h1>Listing lists</h1>


<%= link_to 'New List', new_list_path, id: "form_link", remote: true %>











<h2>Incomplete Tasks</h2>
<div class="tasks" id="incomplete_tasks">
  <%= render @incomplete_tasks %>
</div>

<h2>Comlpete Tasks</h2>
<div class="tasks" id="complete_tasks">
  <%= render @complete_tasks %>
</div>

app/views/lists/new.html.erb
<h1>New list</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path %>

app/views/lists/new.js.erb
$('#form_link').hide().after('<%= j render("form") %>');

app/views/lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @list.task %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @list.complete %>
</p>

<%= link_to 'Edit', edit_list_path(@list) %> |
<%= link_to 'Back', lists_path %>

app/views/lists/update.js.erb
<% if @list.complete? %>
  $('#edit_list_<%= @list.id %>').appendTo('#complete_tasks');
<% else %>
  $('#edit_list_<%= @list.id %>').appendTo('#incomplete_tasks');
<% end %>